<a href="https://colab.research.google.com/github/gsipoczy/tensorflow_course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
2+2

4

# Start something

In [3]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
# Create a first tensor with tf.constant()
scalar = tf.constant(7)
print(scalar, type(scalar))


tf.Tensor(7, shape=(), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
# Check the number of dimensions
print(scalar.ndim)

0


In [6]:
# Now create a vector (1D array)
vector = tf.constant([10,10])
print(vector, type(vector), vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'> 1


In [7]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Create a matrix
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Matrix with data type
matrix2 = tf.constant([[1,2],[3,4],[5,6]], dtype = tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [12]:
# 3D tensor 3x3x3 filled with random numbers 1-100
random_tensor = tf.constant(tf.random.uniform(shape=(3,3,3), minval=1, maxval=101, dtype=tf.int32))
print(random_tensor)


tf.Tensor(
[[[77  7 54]
  [42 30 61]
  [28 40 64]]

 [[56 33 97]
  [38 21  9]
  [13  2 33]]

 [[51 44 80]
  [ 7 16 71]
  [30 53 74]]], shape=(3, 3, 3), dtype=int32)


# So
- scalar: single number, 0D
- vector: 1D array
- matrix: 2D array
- tensor: >2D array