<a href="https://colab.research.google.com/github/gsipoczy/tensorflow_course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import random
import numpy as np
import tensorflow as tf


In [162]:
def info(t):
  print(f"Datatype:\t\t\t{t.dtype}")
  print(f"Number of dimensions:\t\t{t.ndim}")
  print(f"Shape:\t\t\t\t{t.shape}")
  print(f"Elements along 0 axis:\t\t{t.shape[0]}")
  print(f"Elements along last axis:\t{t.shape[-1]}")
  print(f"Total number of elements:\t{tf.size(t)}")

# Start something

In [125]:
# Import Tensorflow
print(tf.__version__)

2.19.0


In [126]:
# Create a first tensor with tf.constant()
scalar = tf.constant(7)
print(scalar, type(scalar))


tf.Tensor(7, shape=(), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [127]:
# Check the number of dimensions
print(scalar.ndim)

0


In [128]:
# Now create a vector (1D array)
vector = tf.constant([10,10])
print(vector, type(vector), vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'> 1


In [129]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [130]:
# Create a matrix
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [131]:
matrix.ndim

2

In [132]:
# Matrix with data type
matrix2 = tf.constant([[1,2],[3,4],[5,6]], dtype = tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [133]:
# 3D tensor 3x3x3 filled with random numbers 1-100
random_tensor = tf.constant(tf.random.uniform(shape=(3,3,3), minval=1, maxval=101, dtype=tf.int32))
print(random_tensor)


tf.Tensor(
[[[95 91 45]
  [45 43 11]
  [73 13  3]]

 [[34 36 87]
  [88 80 82]
  [63 17  4]]

 [[88 56  5]
  [ 3 73 52]
  [97 15 45]]], shape=(3, 3, 3), dtype=int32)


# So
- scalar: single number, 0D
- vector: 1D array
- matrix: 2D array
- tensor: >2D array

# `tf.variable`
- tensor created as `tf.constant` cannot be modified after creation
- tensor created as `tf.Variable` can

In [134]:
changable = tf.Variable([10,7])
unchangable = tf.constant([10,7])
changable, unchangable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [135]:
# Change an element

try:
  unchangable[0] = 7
except Exception as e:
  print(e)

changable[0].assign(7)
changable

'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [136]:
# So try with the unchangable
try:
  unchangable[0] = 7
except Exception as e:
  print(e)

try:
  unchangable[0].assign(7)
except Exception as e:
  print(e)


'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


# Random content tensor with random size
Use: before starting the __pattern -> rule__ cycle (__fitting__), the tensors representing the __weights and biases__ has to be initialized with something value.

These initial values can be constant, but also can be filled randomly.

`tf.normal()` fills the values with _normal distribution_

In [137]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [138]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

Are these tensors the same (size and values)?

In [139]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Let's change the seed

In [140]:
random_3 = tf.random.Generator.from_seed(55)
random_3 = random_3.normal(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.04082382,  2.6791053 ],
       [ 1.0914806 ,  0.33149615],
       [-0.67958915,  0.44723678]], dtype=float32)>

In [141]:
random_1 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

- using the same seed, random tensors with the __same__ values can be created
- different seed give different random results

# Shuffeling the order of elements
Reason:
- Dataset with 15000 images
- The first 10000 are dogs
- The last 5000 are cats

If we start the fitting only with dogs, the model 'uses to' too much to dogs and will know nothing about cats.

In [142]:
not_shuffled = tf.constant(tf.random.uniform(shape=(3, 2), minval=1, maxval=10, dtype=tf.int32))
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 4],
       [4, 4],
       [3, 7]], dtype=int32)>

shuffle it:

In [143]:
shuffled = tf.random.shuffle(not_shuffled)
print(shuffled)
print(not_shuffled)

tf.Tensor(
[[7 4]
 [3 7]
 [4 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[7 4]
 [4 4]
 [3 7]], shape=(3, 2), dtype=int32)


hmmm... it shuffled only the rows, but not within rows...

From the documentation:

'... randomly shuffles the tensor __along the first dimension__ ...'

It makes absolute sense, e.g. if this tensor has 15000 rows, each row is an image of dogs and cats: we want to change only the __order of the pictures__, but do not want to mess with the pictures themselves.

Try the shuffling several times

In [144]:
print(tf.random.shuffle(not_shuffled))
print(tf.random.shuffle(not_shuffled))
print(tf.random.shuffle(not_shuffled))

tf.Tensor(
[[4 4]
 [3 7]
 [7 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[7 4]
 [3 7]
 [4 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 7]
 [4 4]
 [7 4]], shape=(3, 2), dtype=int32)


What if we set a seed?

In [145]:
print(tf.random.shuffle(not_shuffled, seed = 42))
print(tf.random.shuffle(not_shuffled, seed = 42))
print(tf.random.shuffle(not_shuffled, seed = 42))

tf.Tensor(
[[3 7]
 [7 4]
 [4 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[3 7]
 [7 4]
 [4 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[4 4]
 [3 7]
 [7 4]], shape=(3, 2), dtype=int32)


still changing. Let's set the seed outside

In [146]:
tf.random.set_seed(42)                                    # Global seed
print(tf.random.shuffle(not_shuffled, seed = 42))         # Operatin level seed
tf.random.set_seed(42)
print(tf.random.shuffle(not_shuffled, seed = 42))
tf.random.set_seed(42)
print(tf.random.shuffle(not_shuffled, seed = 42))

tf.Tensor(
[[7 4]
 [4 4]
 [3 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[7 4]
 [4 4]
 [3 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[7 4]
 [4 4]
 [3 7]], shape=(3, 2), dtype=int32)


So if we want to set the same shuffling, __both the global and operation seed must be set every time of run (the global too!)__

# Create tensors from NumPy arrays

Main difference between Numpy arrays and TF tensors: tensors can run on GPU/TPU much faster

In [147]:
# Create with tf
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [148]:
# zeros
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [149]:
# Convert a Numpy array to tf tensor
numpy_A = np.random.randint(100, size=(24,))
print(numpy_A)
print()
A = tf.constant(numpy_A, shape = (2,3,4))
print(A)
print()
B = tf.constant(numpy_A, shape = (3, 8))
print(B)
print()

[89 89 93 47  1 84 16 39 36 72 33 15  9 48 97 16 99 37  2  6 65 79 78 11]

tf.Tensor(
[[[89 89 93 47]
  [ 1 84 16 39]
  [36 72 33 15]]

 [[ 9 48 97 16]
  [99 37  2  6]
  [65 79 78 11]]], shape=(2, 3, 4), dtype=int64)

tf.Tensor(
[[89 89 93 47  1 84 16 39]
 [36 72 33 15  9 48 97 16]
 [99 37  2  6 65 79 78 11]], shape=(3, 8), dtype=int64)



In [150]:
npa = np.random.randint(100, size=(3, 8))
print(npa)
print()
print(tf.constant(npa))


[[ 1 85 14 67 67 69 16 17]
 [42 14 53 91 19 41 62 77]
 [25 59 59 22 83 61 45 27]]

tf.Tensor(
[[ 1 85 14 67 67 69 16 17]
 [42 14 53 91 19 41 62 77]
 [25 59 59 22 83 61 45 27]], shape=(3, 8), dtype=int64)


# Getting information of tensors
* Shape - size of dimensions, (2,3,4) - `.shape`
* Rank - number of dimensions - `.ndim`
* Axis or Dimension
* Size

In [166]:
rank_4_tensor = tf.random.uniform(shape=[3,3,4,5], minval=0, maxval=10)
rank_4_tensor

# 2 3D rectangles (one 4D rectangle)
# every 3D rectangles has 3 matrices
# every matrix has 4 rows and 5 columns

<tf.Tensor: shape=(3, 3, 4, 5), dtype=float32, numpy=
array([[[[7.413678  , 6.2854624 , 0.17384648, 3.431449  , 5.1063766 ],
         [3.777541  , 0.7321596 , 0.21370292, 2.8717709 , 4.710616  ],
         [6.936141  , 0.7321334 , 9.325121  , 2.0843053 , 7.010583  ],
         [4.585639  , 8.596262  , 9.293433  , 2.0291913 , 7.6865506 ]],

        [[6.001602  , 2.7039742 , 8.818062  , 0.5365038 , 4.2274466 ],
         [8.903778  , 7.8870335 , 1.0165584 , 1.9408834 , 2.7896714 ],
         [3.9512634 , 1.2235212 , 3.8412368 , 9.455296  , 7.759467  ],
         [9.444235  , 0.4296565 , 4.746096  , 6.548251  , 5.657116  ]],

        [[1.3858628 , 3.004663  , 3.311677  , 1.2907016 , 6.435652  ],
         [4.5473957 , 6.8881893 , 3.0203617 , 4.9152803 , 2.6529062 ],
         [7.1227407 , 7.2297087 , 1.8866003 , 2.4155617 , 8.013924  ],
         [9.717447  , 7.0450697 , 2.8954244 , 5.491171  , 0.50623417]]],


       [[[1.928184  , 4.541731  , 2.1889174 , 8.72438   , 5.6308484 ],
         [3.167

In [167]:
info(rank_4_tensor)

Datatype:			<dtype: 'float32'>
Number of dimensions:		4
Shape:				(3, 3, 4, 5)
Elements along 0 axis:		3
Elements along last axis:	5
Total number of elements:	180


# Indexing

### Get the first 2 elements from each dimension

In [168]:
# Indexing a python list:
plist = [1,2,3,4]
plist[:2]

[1, 2]

In [169]:
# Do it with our nice tensor:
t4t = tf.random.uniform(shape=[3,3,4,5], minval=0, maxval=10)
t4t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[7.402308  , 3.3938193 ],
         [4.260056  , 6.2890387 ]],

        [[6.792555  , 0.97527266],
         [4.1212583 , 7.31905   ]]],


       [[[6.6961646 , 8.815127  ],
         [2.3811603 , 1.3453543 ]],

        [[9.756613  , 7.968651  ],
         [4.11615   , 2.4478185 ]]]], dtype=float32)>

### Get the first element from each dimension except for the last one

In [170]:
t4t[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=
array([[[[7.402308 , 3.3938193, 5.692506 , 4.481139 , 2.9285502]]]],
      dtype=float32)>

In [173]:
t4t[:1, 1:, 1:3, :]

<tf.Tensor: shape=(1, 2, 2, 5), dtype=float32, numpy=
array([[[[4.1212583 , 7.31905   , 9.341894  , 5.2981224 , 9.664817  ],
         [8.83912   , 1.0578597 , 4.443958  , 7.851516  , 4.7332516 ]],

        [[8.286293  , 8.77372   , 5.3198028 , 0.3594303 , 0.39866686],
         [8.335347  , 7.7236996 , 8.20483   , 3.6137402 , 3.729055  ]]]],
      dtype=float32)>

In [174]:
t2t = tf.random.uniform(shape=[2,2], minval=0, maxval=10)
t2t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8.03156  , 4.9777737],
       [3.7054038, 9.118673 ]], dtype=float32)>

In [175]:
# Get the LAST element of each dimension
t2t[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.9777737, 9.118673 ], dtype=float32)>

In [176]:
t2t[-1, :]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.7054038, 9.118673 ], dtype=float32)>

In [177]:
# Add a new dimension
t3t = t2t[... , tf.newaxis]
t3t

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[8.03156  ],
        [4.9777737]],

       [[3.7054038],
        [9.118673 ]]], dtype=float32)>

In [180]:
# Other dims
print(t2t[:, :, tf.newaxis])
print()

print(t2t[:, tf.newaxis, :])
print()

print(t2t[tf.newaxis, :, :])
print()

tf.Tensor(
[[[8.03156  ]
  [4.9777737]]

 [[3.7054038]
  [9.118673 ]]], shape=(2, 2, 1), dtype=float32)

tf.Tensor(
[[[8.03156   4.9777737]]

 [[3.7054038 9.118673 ]]], shape=(2, 1, 2), dtype=float32)

tf.Tensor(
[[[8.03156   4.9777737]
  [3.7054038 9.118673 ]]], shape=(1, 2, 2), dtype=float32)



### Alternative to `tf.newaxis`: `tf.expand_dims()`

In [181]:
# Expand the final axis - actually same as t2t[:, :, tf.newaxis]
tf.expand_dims(t2t, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[8.03156  ],
        [4.9777737]],

       [[3.7054038],
        [9.118673 ]]], dtype=float32)>